# This workflow will install Python dependencies, run tests and lint
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test

on:
  push:
    branches: [main, workflowtesting]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.3.0
#       - name: Set up Python 3.9
#         id: python
#         uses: actions/setup-python@v4
#         with:
#           python-version: 3.9
#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements_lint.txt
#       - name: Lint
#         run: pre-commit run
      - name: Home Assistant builder
        uses: home-assistant/builder@2022.11.0
